### PR TITLE
QIP5: Interlinks in Quai

### PR DESCRIPTION
**Pull request by gameofpointers**

### CODE REVIEW

**Review by alanorwick — COMMENTED** [review]
Is l = 4 sufficient? Theorem 8 in the paper outlines log(C) as the most amount of levels possible. If we anticipate 10 min prime blocks for 30 years:
`log(6 * 60 * 24 * 365 * 30)`

That's closer to 8. Is there a trade off in sparseness / data we're optimizing for?

**Review by alanorwick — COMMENTED** [review]
We may also want to expand more on how we intend to implement the SPV-like mechanism for interlink proving.

**Review by wizeguyy — CHANGES_REQUESTED** [review]
This QIP cannot be merged without defining proof structure, as well as prover and verifier algorithms.

Also, not sure this should be done in a QIP. Its probably better to define this new cryptographic protocol in a paper of its own, so that it can have all the necessary math and proofs for peer review, without distracting from the purpose of this QIP: _to recommend a set of changes for the community to adopt._

So, IMO it would be better to:
* remove any math or proofs, and link to the paper instead
* keep the description of the interlink structure and new header structure
* add a description of the NiPoPoEM proof structure, as well as the prover and verifier routines

**Comment by wizeguyy** [comment]
closing based in your request IRL

**Pull request closed without merging**
